#!/bin/sh
BASE_DIR="$(dirname "$BASH_SOURCE")"

# 0. upload images
cd $BASE_DIR"/source/posts"
[ -e media ] && pngquant -f -v --quality=60 --ext .png media/*.png

upload --debug
cd -

1. compile
cd $BASE_DIR
python3 scripts/main.py source
cd -