#!/bin/sh
BASE_DIR="$(dirname "$BASH_SOURCE")"

# 0. upload images
cd $BASE_DIR"/source/posts"
[ -f media ] && tinify media/* || echo "No images to tinify."
upload --debug
cd -

# 1. compile
cd $BASE_DIR
python3 scripts/main.py source
cd -