Add-extensions-to-build-scripts:
  abstract: 本质上还是要搞清楚 KTS 是怎么运行的
  bilibili_id: BV1BU4y1b7Wk
  date: 2021/04/18
  date_time: 2021/04/18
  file_name: Add-extensions-to-build-scripts
  keywords: Gradle Groovy Kotlin KTS
  tags: 'Gradle|Groovy|Kotlin|KTS '
  title: 如何为 Gradle 的 KTS 脚本添加扩展？
Java17-Updates-01-intro:
  abstract: 2021 年 9月 23 日，Java 17 发布了，更新的内容还真不少，足足肝了我一星期才把这些内容整理完。
  date: 2021/09/26
  date_time: 2021/09/26
  file_name: Java17-Updates-01-intro
  keywords: Java Java17
  position: 298
  tags: 'Java|Java17 '
  title: Java 17 更新（1）：更快的 LTS 节奏
Java17-Updates-02-strictfp:
  abstract: strictfp 可能是最没有存在感的关键字了，很多人写了多年 Java 甚至都不知道它的存在。接下来，它也没有必要继续存在了。
  date: 2021/09/26
  date_time: 2021/09/26
  file_name: Java17-Updates-02-strictfp
  keywords: Java Java17
  position: 409
  tags: 'Java|Java17|strictfp '
  title: Java 17 更新（2）：没什么存在感的 strictfp 这回算是回光返照了
Java17-Updates-03-random:
  abstract: JDK 当中的随机数生成器其实对于普通开发者来讲基本够用，不过对于一些比较复杂的场景来讲，原有的类结构对扩展并不是很友好。
  date: 2021/09/27
  date_time: 2021/09/27
  file_name: Java17-Updates-03-random
  keywords: Java Java17
  position: 407
  tags: 'Java|Java17|random '
  title: Java 17 更新（3）：随机数生成器来了一波稳稳的增强
Java17-Updates-04-mac:
  abstract: mac 这几年的变化还是挺大的，Java 也必须做一些适应性的变化，不然都没法外接高分显示器了。
  date: 2021/09/27
  date_time: 2021/09/27 08:00:00
  file_name: Java17-Updates-04-mac
  keywords: Java Java17
  position: 348
  tags: 'Java|Java17|mac '
  title: Java 17 更新（4）：这波更新，居然利好 mac 用户
Java17-Updates-05-removed:
  abstract: 这次更新有好几条关于移除老代码的，我们来集中介绍一下。
  date: 2021/09/28
  date_time: 2021/09/28
  file_name: Java17-Updates-05-removed
  keywords: Java Java17
  position: 346
  tags: 'Java|Java17|applet|rmi|aot|jit|SecurityManager '
  title: Java 17 更新（5）：历史包袱有点儿大，JDK 也在删代码啦
Java17-Updates-06-internals:
  abstract: 说实话，我们总是用人家 JDK 的内部 API，是不是有点儿欺负人。
  date: 2021/10/02
  date_time: 2021/10/02 19:10:55
  file_name: Java17-Updates-06-internals
  keywords: Java Java17
  position: 345
  tags: 'Java|Java17|internal '
  title: Java 17 更新（6）：制裁！我自己私有的 API 你们怎么随便一个人都想用？
Java17-Updates-07-switch:
  abstract: Java 的 switch 又加强啦！
  date: 2021/10/02
  date_time: 2021/10/02 19:10:56
  file_name: Java17-Updates-07-switch
  keywords: Java Java17
  position: 250
  tags: 'Java|Java17|switch '
  title: Java 17 更新（7）：模式匹配要支持 switch 啦
Java17-Updates-08-sealedclass:
  abstract: Java 看 Kotlin 实现了密封类，马上给自己搞了密封类和密封接口，Kotlin 一看也立马支持了密封接口。
  date: 2021/10/02
  date_time: 2021/10/02 19:10:57
  file_name: Java17-Updates-08-sealedclass
  keywords: Java Java17
  position: 345
  tags: 'Java|Java17|sealed class '
  title: Java 17 更新（8）：密封类终于转正
Java17-Updates-09-foreignapi-memory:
  abstract: 使用 Unsafe 直接访问堆外内存存在各种安全性问题，对于使用者的要求也比较高，不太适合在业务当中广泛使用。于是，Java 在新孵化的 API
    当中提供了更安全的方案。
  date: 2021/10/02
  date_time: 2021/10/02 19:10:58
  file_name: Java17-Updates-09-foreignapi-memory
  keywords: Java Java17
  position: 478
  tags: 'Java|Java17|direct memory '
  title: Java 17 更新（9）：Unsafe 不 safe，我们来一套 safe 的 API 访问堆外内存
Java17-Updates-10-foreignapi-callfunction:
  abstract: 'JNI 不安全还繁琐，所以 Java 搞了一套新的 API，结果把这事儿搞得更复杂了。。。 '
  date: 2021/10/02
  date_time: 2021/10/02 20:10:08
  file_name: Java17-Updates-10-foreignapi-callfunction
  keywords: Java Java17
  position: 357
  tags: 'Java|Java17|foreign function api '
  title: Java 17 更新（10）：访问外部函数的新 API，JNI 要凉了？
Java17-Updates-11-vector:
  abstract: Java 17 将继续孵化对矢量计算的支持。
  date: 2021/10/02
  date_time: 2021/10/02 20:10:09
  file_name: Java17-Updates-11-vector
  keywords: Java Java17
  position: 273
  tags: 'Java|Java17 '
  title: Java 17 更新（11）：支持矢量运算，利好科学计算？
Java17-Updates-12-contextserialfilter:
  abstract: Java 的序列化机制虽然有些问题，不过毕竟亲儿子，更新怎么能落下呢。
  date: 2021/10/02
  date_time: 2021/10/02 20:10:10
  file_name: Java17-Updates-12-contextserialfilter
  keywords: Java Java17
  position: 345
  tags: 'Java|Java17 '
  title: Java 17 更新（12）：支持上下文的序列化过滤器，又一次给序列化打补丁
android-studio-shortcuts:
  abstract: 有关 Android Studio 快捷键，看这个视频就够了
  bilibili_id: BV1g64y1279B
  date: 2021/05/10
  date_time: 2021/05/10
  file_name: android-studio-shortcuts
  keywords: IDE 快捷键
  tags: 'Android Studio|技巧|快捷键 '
  title: '"[Android Studio 技巧] 快捷键的使用"'
basic-coroutines:
  abstract: 假定你对协程（Coroutine）一点儿都不了解，通过阅读本文看看是否能让你明白协程是怎么一回事。
  date: 2019/04/01
  date_time: 2019/04/01
  file_name: basic-coroutines
  keywords: Kotlin 协程 入门
  tags: ''
  title: 破解 Kotlin 协程(1) - 入门篇
c-println:
  abstract: Kotlin 当中的 println 非常好用，可是 C 当中我们常用的 printf 却总是需要格式化字符，并且需要手动提供换行符。
  date: 2020/06/14
  date_time: 2020/06/14
  file_name: c-println
  keywords: C 宏 泛型 println
  tags: 'C|macro| '
  title: C 语言版的 println？
coroutine-android:
  /github.com: enbandari
  abstract: Android 上面使用协程来替代回调或者 RxJava 实际上是一件非常轻松的事儿，我们甚至可以在更大的范围内结合 UI 的生命周期做控制协程的执行状态~
  date: 2019/05/27
  date_time: 2019/05/27
  file_name: coroutine-android
  keywords: Kotlin 协程 Android Anko
  tags: 'Kotlin|Coroutine|Android '
  title: '破解 Kotlin 协程(8) - Android 篇 '
coroutine-cancellation:
  abstract: 协程的任务的取消需要靠协程内部调用的协作支持，这就类似于我们线程中断以及对中断状态的响应一样。
  date: 2019/04/30
  date_time: 2019/04/30
  file_name: coroutine-cancellation
  keywords: Kotlin 协程 协程取消 任务停止
  tags: ''
  title: '破解 Kotlin 协程(5) - 协程取消篇 '
coroutine-channel:
  abstract: '`Channel` 实际上就是协程在生产消费者模型上的应用，把过去你用 `BlockingQueue` 实现的功能替换成 `Channel`，也许会有新的发现~'
  date: 2019/09/16
  date_time: 2019/09/16
  file_name: coroutine-channel
  keywords: Kotlin 协程 Channel 生产消费者
  tags: ''
  title: '破解 Kotlin 协程(9) - Channel 篇 '
coroutine-dispatchers:
  abstract: 上一篇我们知道了协程启动的几种模式，也通过示例认识了 `launch` 启动协程的使用方法，本文将延续这些内容从调度的角度来进一步为大家揭示协程的奥义。
  date: 2019/04/11
  date_time: 2019/04/11
  file_name: coroutine-dispatchers
  keywords: Kotlin 异步编程 协程
  tags: ''
  title: '破解 Kotlin 协程(3) - 协程调度篇 '
coroutine-exceptions:
  abstract: 异步代码的异常处理通常都比较让人头疼，而协程则再一次展现了它的威力。
  date: 2019/04/23
  date_time: 2019/04/23
  file_name: coroutine-exceptions
  keywords: Kotlin 协程 异常处理
  tags: ''
  title: '破解 Kotlin 协程(4) - 异常处理篇 '
coroutine-flow:
  abstract: '`Flow` 就是 Kotlin 协程与响应式编程模型结合的产物，你会发现它与 RxJava 非常像，二者之间也有相互转换的 API，使用起来非常方便。'
  date: 2020/03/14
  date_time: 2020/03/14
  file_name: coroutine-flow
  keywords: Kotlin 协程 Flow 响应式编程 RxJava
  tags: 'Kotlin|Flow|RxJava '
  title: 破解 Kotlin 协程(11) - Flow 篇
coroutine-implementations:
  abstract: 所谓知己知彼，百战不殆。为了搞清楚 Kotlin 协程是怎么回事，我们也来看看其他语言的协程是怎么实现的。
  date: 2019/12/01
  date_time: 2019/12/01
  file_name: coroutine-implementations
  keywords: 协程 分类
  tags: ''
  title: 破解 Kotlin 协程 番外篇(2) - 协程的几类常见的实现
coroutine-select:
  abstract: Select 并不是什么新鲜概念，我们在 IO 多路复用的时候就见过它，在 Java NIO 里面也见过它。接下来给各位介绍的是 Kotlin
    协程的 Select。
  date: 2020/02/03
  date_time: 2020/02/03
  file_name: coroutine-select
  keywords: Kotlin 协程 Select 多路复用
  tags: 'Kotlin|Coroutines|Select '
  title: '破解 Kotlin 协程(10) - Select 篇 '
coroutine-sequence:
  abstract: 说出来你可能不信，Kotlin 1.1 协程还在吃奶的时候，Sequence 就已经正式推出了，然而，Sequence 生成器的实现居然有协程的功劳。
  date: 2019/05/26
  date_time: 2019/05/26
  file_name: coroutine-sequence
  keywords: Kotlin 协程 序列 Sequence
  tags: ''
  title: '破解 Kotlin 协程(7) - 序列生成器篇 '
coroutine-suspend:
  abstract: 协程的挂起最初是一个很神秘的东西，因为我们总是用线程的概念去思考，所以我们只能想到阻塞。不阻塞的挂起到底是怎么回事呢？说出来你也许会笑~~（哭？。。抱歉这篇文章我实在是没办法写的更通俗易懂了，大家一定要亲手实践！）
  date: 2019/05/07
  date_time: 2019/05/07
  file_name: coroutine-suspend
  keywords: Kotlin 协程 协程挂起 任务挂起 suspend 非阻塞
  tags: ''
  title: '破解 Kotlin 协程(6) - 协程挂起篇 '
coroutine-why-so-called-lightweight-thread:
  abstract: 接触新概念，最好的办法就是先整体看个大概，再回过头来细细品味。
  date: 2019/10/19
  date_time: 2019/10/19
  file_name: coroutine-why-so-called-lightweight-thread
  keywords: Kotlin 协程 协程 stackful stackless
  tags: ''
  title: 破解 Kotlin 协程 番外篇(1) - 协程为什么被称为『轻量级线程』？
coroutines-start-mode:
  abstract: 现在你已经知道协程大概是怎么回事了，也应该想要自己尝试一把了吧。本文将为大家详细介绍协程的几种启动模式之间的不同，当然，我不打算现在就开始深入源码剖析原理，大家只需要记住这些规则就能很好的使用协程了。
  date: 2019/04/08
  date_time: 2019/04/08
  file_name: coroutines-start-mode
  keywords: Kotlin 协程 启动模式
  tags: ''
  title: 破解 Kotlin 协程(2) - 协程启动篇
deprecated-kotlin-android-extensions:
  abstract: 伴随了我们这么多年的 KAE，就这么要离开我们了？
  date: 2020/11/07
  date_time: 2020/11/07
  file_name: deprecated-kotlin-android-extensions
  keywords: Kotlin 1.4 KAE
  tags: 'Kotlin|Android|News '
  title: '要再见了吗，Kotlin Android Extension '
google-preferred-kotlin:
  abstract: 如果你觉得天气热不舒服，那一定是享受过凉爽之后才会有的感觉。你没有意识到 Java 的问题，那正说明你应该试试 Kotlin。
  date: 2019/05/10
  date_time: 2019/05/10
  file_name: google-preferred-kotlin
  keywords: Android Kotlin Google Java
  title: 如何看待 Google 将 Kotlin 作为 Android 开发首选语言？
gradle-migrate-to-kts:
  abstract: 接下来我们就把这个示例工程的 Gradle 脚本用 KTS 改写
  bilibili_id: BV1Kf4y1p7zq
  date: 2021/04/18
  date_time: 2021/04/18
  file_name: gradle-migrate-to-kts
  keywords: Gradle Groovy Kotlin KTS
  tags: 'Gradle|Groovy|Kotlin|KTS '
  title: 快速迁移 Gradle 脚本至 KTS
gradle-task-syntax:
  abstract: 任务名居然是以标识符的形式写出来的，你们难道没有觉得奇怪吗？
  bilibili_id: BV1ib4y1D74X
  date: 2021/04/12
  date_time: 2021/04/12
  file_name: gradle-task-syntax
  keywords: Gradle Groovy
  tags: 'Gradle|Groovy '
  title: Gradle 创建 Task 的写法不是 Groovy 的标准语法吧？
how-to-read-the-book-of-coroutines:
  abstract: 趁着面试官还没看，赶紧深入了解一下~~
  date: 2021/01/31
  date_time: 2021/01/31
  file_name: how-to-read-the-book-of-coroutines
  keywords: Kotlin 协程
  tags: 'Kotlin|协程 '
  title: 《深入理解 Kotlin 协程》这书该怎么读？
kotlin-1.4-preview:
  abstract: Kotlin 1.4 没有特别重大的更新，更多的是细节的优化。
  date: 2020/03/26
  date_time: 2020/03/26
  file_name: kotlin-1.4-preview
  keywords: Kotlin 1.4 新版本
  tags: 'Kotlin|Release|News '
  title: Kotlin 1.4 新特性预览
kotlin-2019-whats-new:
  abstract: Kotlin 已经很成熟了。有多成熟呢？Kotlin Team 现在的重心已经是在为各个领域内的 Kotlin 实践提供支持了。
  date: 2019/12/23
  date_time: 2019/12/23
  file_name: kotlin-2019-whats-new
  keywords: Kotlin 新特性 近况
  title: Kotlin 最近怎么样了
kotlin-forum-mobile:
  abstract: 我也是刚发现的！再也不用担心自己抛出的问题被QQ群的水友给冲掉啦！
  date: 2019/10/22
  date_time: 2019/10/22
  file_name: kotlin-forum-mobile
  keywords: Kotlin 中文论坛
  title: Kotlin 中文论坛的使用技巧
kotlin-inline-class-improvements:
  abstract: 内联类从 1.3 推出，一直处于实验状态。
  date: 2021/01/18
  date_time: 2021/01/18
  file_name: kotlin-inline-class-improvements
  keywords: Kotlin News
  tags: 'Kotlin|News|inline class '
  title: Kotlin 1.4.30-M1 增强的内联类是个什么东西？
kotlin-intersect-type:
  /www.bennyhuo.com/2020/03/26: kotlin-1.4-preview
  abstract: Kotlin 1.4 会默认使用一套新的类型推导算法，类型系统也相比之前更强大了。
  date: 2020/04/06
  date_time: 2020/04/06
  file_name: kotlin-intersect-type
  keywords: Kotlin 1.4 类型系统
  tags: 'Kotlin|Type '
  title: Kotlin 新版本也有了交叉类型和联合类型？
kotlin-map-default:
  abstract: Map 的 Value 类型是一个可空类型，Kotlin 早就想好了怎么帮你优雅地面对它。
  date: 2020/06/09
  date_time: 2020/06/09
  file_name: kotlin-map-default
  keywords: Kotlin Map
  tags: 'Kotlin|Map '
  title: Kotlin 为 Map 提供的那些默认值相关的扩展，你用过吗？
kotlin-native-android-mpp:
  abstract: 前不久有个兄弟问有没有可能把之前 Native 写 Jni 的工程改造成 Gradle 的。正好借此机会把之前的工程整理得更完整一些。
  date: 2020/04/19
  date_time: 2020/04/19
  file_name: kotlin-native-android-mpp
  keywords: Kotlin Kotlin-Native Jni 跨平台
  tags: 'Kotlin|Kotlin-Native|MPP '
  title: Kotlin Native 写 Jni 第三弹：改造成 MPP 的工程结构
kotlin-native-introduction:
  abstract: 一直想写点儿 Kotlin-Native 相关的话题，今天开始~
  date: 2020/07/15
  date_time: 2020/07/15
  file_name: kotlin-native-introduction
  keywords: Kotlin-Native
  tags: 'Kotlin|Native '
  title: 闲聊 Kotlin-Native (0) - 我们为什么应该关注一下 Kotlin Native？
kotlin-news-202002:
  abstract: Kotlin 官网这次更新可以算是历史上最大的一次了，跨平台、数据科学等内容也搬到了最前面。
  date: 2020/02/13
  date_time: 2020/02/13
  file_name: kotlin-news-202002
  keywords: Kotlin 更新 移动端跨平台 数据科学
  tags: 'Kotlin|News '
  title: Kotlin 官网大变样？这是要干啥？
kotlin-news-202010:
  abstract: Kotlin 的发展可以认为是正式进入了下一个阶段。
  date: 2020/10/19
  date_time: 2020/10/19
  file_name: kotlin-news-202010
  keywords: Kotlin News
  tags: 'Kotlin|News '
  title: 说说最近官方公布的 Kotlin 的动态
kotlin-sealed-interface:
  abstract: 密封类是 Kotlin 的老成员了，现在也可以有密封接口了。
  date: 2021/01/23
  date_time: 2021/01/23
  file_name: kotlin-sealed-interface
  keywords: Kotlin News
  tags: 'Kotlin|News|sealed interface '
  title: Kotlin 1.4.30-RC 密封接口来啦！
kotlin-swift-property-delegate:
  abstract: Swift 的属性代理，见识一下
  date: 2020/05/08
  date_time: 2020/05/08
  file_name: kotlin-swift-property-delegate
  keywords: Kotlin Swift Property
  tags: 'Kotlin|Swift|Property '
  title: 'Kotlin 的 Property Delegate 与 Swift 的 Property Wrapper '
lazy-evaluation:
  abstract: “懒”是程序员最优秀的品质之一，程序也是如此。
  date: 2020/05/23
  date_time: 2020/05/23
  file_name: lazy-evaluation
  keywords: Kotlin Swift Property
  tags: 'Kotlin|Swift|Scala|Lazy '
  title: Kotlin、Swift、Scala 的延迟求值
sam-meets-package-visibility:
  abstract: SAM 转换是很香，不过还是要小心遇到坑
  bilibili_id: BV1wB4y1g79W
  date: 2021/06/04
  date_time: 2021/06/04
  file_name: sam-meets-package-visibility
  keywords: Java Kotlin SAM
  tags: 'Java|Kotlin|SAM '
  title: 重构代码的时候千万小心，SAM 转换可能会引发一个奇怪的运行时类不能访问的异常
summary-2021:
  abstract: 很快啊，2021 年就过去了 ……
  date: 2022/01/20
  date_time: 2022/01/20 14:01:22
  file_name: summary-2021
  keywords: 2021 总结
  position: 180
  tags: '2021 '
  title: 2021 总结 - bennyhuo
swift-coroutines-01-intro:
  abstract: 2021 年 9 月 20 日，Apple 发布了 Swift 5.5，这个版本当中最亮眼的特性就是对 async await 的支持了。
  date: 2021/10/11
  date_time: 2021/10/11 21:10:53
  file_name: swift-coroutines-01-intro
  group: swift-coroutines
  keywords: Swift Swift5.5
  position: 265
  tags: 'Swift|Coroutines|async await '
  title: 闲话 Swift 协程（1）：Swift 协程长什么样？
swift-coroutines-02-wrap-callback:
  abstract: 最理想的情况下，系统、第三方框架当中使用回调的 API 都最好在一夜之间改成 async 函数，显然这不太现实。
  date: 2021/10/13
  date_time: 2021/10/13 21:10:14
  file_name: swift-coroutines-02-wrap-callback
  group: swift-coroutines
  keywords: Swift Swift5.5
  position: 288
  tags: 'Swift|Coroutines|async await '
  title: 闲话 Swift 协程（2）：将回调改写成 async 函数
swift-coroutines-03-call-async-func:
  abstract: 异步函数需要被异步函数调用，这听上去就是一个鸡生蛋蛋生鸡的问题。关键的问题在于，第一个异步函数从哪儿来？
  date: 2022/01/21
  date_time: 2022/01/21 22:01:01
  file_name: swift-coroutines-03-call-async-func
  group: swift-coroutines
  keywords: Swift Swift5.5
  position: 302
  tags: 'Swift|Coroutines|async await '
  title: 闲话 Swift 协程（3）：在程序当中调用异步函数
swift-coroutines-04-structured-concurrency:
  abstract: 上一篇文章我们提到了结构化并发，这听上去很高级。
  date: 2022/01/22
  date_time: 2022/01/22 21:01:22
  file_name: swift-coroutines-04-structured-concurrency
  group: swift-coroutines
  keywords: Swift Swift5.5
  position: 213
  tags: 'Swift|Coroutines|async await '
  title: 闲话 Swift 协程（4）：TaskGroup 与结构化并发
swift-coroutines-05-cancellation:
  abstract: 但凡是个任务，就有可能被取消。取消了该怎么办呢？
  date: 2022/01/28
  date_time: 2022/01/28 22:01:40
  file_name: swift-coroutines-05-cancellation
  group: swift-coroutines
  keywords: Swift Swift5.5
  position: 199
  tags: 'Swift|Coroutines|async await '
  title: 闲话 Swift 协程（5）：Task 的取消
swift-coroutines-06-actor:
  abstract: 异步函数大多数情况下会并发地执行在不同的线程，那么线程安全怎么来保证？
  date: 2022/02/12
  date_time: 2022/02/12 06:02:30
  file_name: swift-coroutines-06-actor
  group: swift-coroutines
  keywords: Swift Swift5.5
  position: 239
  tags: 'Swift|Coroutines|async await '
  title: 闲话 Swift 协程（6）：Actor 和属性隔离
swift-coroutines-07-globalactor:
  abstract: 我们已经知道可以使用 actor 来确保数据的线程安全，但对于数据的保护总是需要定义专门的 actor 实例是不是太麻烦了一些？
  date: 2022/02/12
  date_time: 2022/02/12 07:02:30
  file_name: swift-coroutines-07-globalactor
  group: swift-coroutines
  keywords: Swift Swift5.5
  position: 313
  tags: 'Swift|Coroutines|async await '
  title: 闲话 Swift 协程（7）：GlobalActor 和异步函数的调度
swift-coroutines-08-tasklocal:
  abstract: 如果我想要定义一个变量，它的值只在 Task 内部共享，怎么做到呢？
  date: 2022/02/12
  date_time: 2022/02/12 21:02:24
  file_name: swift-coroutines-08-tasklocal
  group: swift-coroutines
  keywords: Swift Swift5.5
  position: 212
  tags: 'Swift|Coroutines|async await '
  title: 闲话 Swift 协程（8）：TaskLocal
swift-coroutines-09-interop:
  abstract: 现在很多 iOS APP 还是用 Objective-C 写的，异步函数在 Objective-C 当中怎么调用也是个问题。
  date: 2022/02/16
  date_time: 2022/02/16 23:02:59
  file_name: swift-coroutines-09-interop
  group: swift-coroutines
  keywords: Swift Swift5.5
  position: 268
  tags: 'Swift|Coroutines|async await '
  title: 闲话 Swift 协程（9）：异步函数与其他语言的互调用
understanding-kotlin-coroutines:
  abstract: 没想到 Kotlin 的协程居然会成为一个有争议的话题，谁让官方材料太少呢。
  date: 2020/06/23
  date_time: 2020/06/23
  file_name: understanding-kotlin-coroutines
  keywords: Kotlin 协程 书
  tags: 'Kotlin|Coroutines '
  title: 我写了一本书，《深入理解 Kotlin 协程》
use-mavencentral-when-jcenter-sunset:
  abstract: 这还真是个大新闻。以后我们只能发 Maven 中央仓库了。
  date: 2021/04/12
  date_time: 2021/04/12
  file_name: use-mavencentral-when-jcenter-sunset
  keywords: 开源 JCenter maven
  tags: 'JCenter|Maven '
  title: JCenter 要下线了，我们的开源库要怎么发到 Maven Central 上？
